package emergence.safety;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

import ontology.Types.ACTIONS;
import core.game.StateObservation;

/**
 * A Safety is a method to check if a action is safe. The different approaches
 * should inherit from this class.
 * 
 * @author spakken
 *
 */
public abstract class ASafety {

	/**
	 * Returns true if the action is safe, false otherwise. Depends on the
	 * different methods used to estimate the safety.
	 * 
	 * @param stateObs
	 * @param a
	 * @return
	 */
	public abstract boolean isSafe(StateObservation stateObs, ACTIONS a);

	/**
	 * Returns all save actions, given a state observation.
	 * 
	 * @param stateObs
	 * @return
	 */
	public Set<ACTIONS> getSafeActions(StateObservation stateObs) {
		return getSafeActions(stateObs, stateObs.getAvailableActions());
	}

	/**
	 * Returns a list which only contains safe actions. It is generated by
	 * deleting all unsafe actions from the given list.
	 * 
	 * @param stateObs
	 * @param actions
	 * @return
	 */
	public Set<ACTIONS> getSafeActions(StateObservation stateObs,
			Collection<ACTIONS> actions) {
		Set<ACTIONS> result = new HashSet<>();
		// for all possible moves
		for (ACTIONS a : actions) {
			if (isSafe(stateObs, a))
				result.add(a);
		}
		return result;
	}

	/**
	 * Returns one safe action.
	 * 
	 * @param stateObs
	 * @return
	 */
	public ACTIONS getOneSafeAction(StateObservation stateObs) {
		return getOneSafeAction(stateObs, stateObs.getAvailableActions());
	}

	/**
	 * Returns a safe action which is in the given list.
	 * 
	 * @param stateObs
	 * @param actions
	 * @return
	 */
	public ACTIONS getOneSafeAction(StateObservation stateObs,
			Collection<ACTIONS> actions) {
		ArrayList<ACTIONS> list = new ArrayList<>(actions);
		Collections.shuffle(list);
		for (ACTIONS a : list) {
			if (isSafe(stateObs, a))
				return a;
		}
		System.out.println("[" + stateObs.getGameTick()
				+ "] NO SAFE ACTION FOUND!");
		return ACTIONS.ACTION_NIL;
	}

	/**
	 * Generate a String object which is used in csv files.
	 */
	public abstract String toCSVString();
}
